<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Grug主页</title>
		<link rel="stylesheet" href="/public/css/bootstrap.min.css">
	</head>
	<body>
		<div style="background:#6F00D2;">
			<div class="container">
				<h3 style="text-align:center; color:#FFF">欢迎访问Grug主页！</h3>
			</div>
		</div>
		<div class="container">
			<h4 class="page-header">欢迎访问Grug的博客：<a href="http://grugblog.sinaapp.com/">瓜哥的博客</a></h4>
			<p>Grug会不定期的更新博客，内容主要涉及PHP、Mysql、Linux等相关知识，希望大家积极评论、探讨，共同学习进步！</p>
			<h4 class="page-header">欢迎关注Grug的微博：<a href="http://weibo.com/chenzeping1016">@默然仰望星空</a></h4>
			<p>Grug现在在新浪微博工作，自家产品嘛，希望大家多多关注~~</p>
		</div>
		
		<script src="/public/js/jquery-1.11.3.min.js"></script>
		<script src="/public/js/bootstrap.min.js"></script>
		<script language="JavaScript">
			$(function(){
				
			});
		</script>
	</body>
</html>