<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>movie thanks</title>
		<link rel="stylesheet" href="/public/css/bootstrap.min.css">
	</head>
	<body>
		<?=$info?>
		<a href="/movie/test/thanks">返回</a>
		<script src="/public/js/jquery-1.11.3.min.js"></script>
		<script src="/public/js/bootstrap.min.js"></script>
		<script language="JavaScript">
			$(function(){

			});
		</script>
	</body>
</html>