<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>瓜哥</title>
		<link rel="stylesheet" href="/public/css/bootstrap.min.css">
	</head>
	<body>
		<h1>
		大家好，我是瓜哥！
		</h1>
	<p><?=$test?></p>
	<p><?=$haha?></p>


	<script src="/public/js/jquery-1.11.3.min.js"></script>
	<script src="/public/js/bootstrap.min.js"></script>
	
	</body>
</html>
